name: lfv
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.13.5

  # HEP / Physics analysis
  - coffea=2025.7.3
  - awkward=2.8.7
  - uproot=5.6.4
  - hist=2.9.0
  - boost-histogram=1.6.1
  - correctionlib=2.7.0
  - vector=1.6.3
  - iminuit=2.31.1
  - mplhep=0.4.0
  - histoprint=2.6.0

  # Distributed computing
  - dask=2025.3.0
  - dask-awkward=2025.5.0
  - dask-histogram=2025.2.0
  - distributed=2025.3.0
  - ndcctools=7.17.0
  - cloudpickle=3.1.1
  - toolz=1.0.0

  # ML
  - xgboost=3.0.4
  - scikit-learn=1.7.1
  - numba=0.61.2

  # Data / IO
  - numpy=2.2.6
  - pandas=2.3.2
  - pyarrow=20.0.0
  - fsspec=2025.5.1
  - xrootd=5.8.4
  - scipy=1.16.1

  # Plotting
  - matplotlib-base=3.10.5
  - bokeh=3.7.3

  # Utilities
  - pyyaml=6.0.2
  - requests=2.32.5
  - tqdm=4.67.1
  - psutil=7.0.0
  - conda-pack=0.8.1
  - rich=14.1.0
  - click=8.2.1
  - packaging=25.0
  - six=1.17.0
  - toml=0.10.2

  - pip
  - pip:
      - appdirs==1.4.4
      - fs==2.4.16
      - fsspec-xrootd==0.5.1
      - xrootdpyfs==2.0.0

